### ISSUE TITLE
Request builder does not support query params for product get

### ISSUE THREAD

**Issue by xemayebenes** [commercetools/nodejs#1065]
### Description

The documentation to the get product says that the url accepts query params for price selection:
https://docs.commercetools.com/http-api-projects-products#get-product-by-id

However, the library throws an error when trying to parse this parameters:

```js
client.execute({
      uri: requestBuilder()
        .products.parse({
          id,
          priceCountry: "CL"
        })

        .build(),
      method: "GET"
    });
```

### Expected Behavior

The uri should be something like `/{projectKey}/products/{id}?priceCountry=CL`

### Current Behavior
The sdk throws an error
`TypeError: this.priceCountry is not a function
        at Object.setParams (/Users/xema/projects/tottus/products/node_modules/@commercetools/api-request-builder/dist/commercetools-api-request-builder.cjs.js:426:44)
        at Object.parse (/Users/xema/projects/tottus/products/node_modules/@commercetools/api-request-builder/dist/commercetools-api-request-builder.cjs.js:1266:21)
        at Object.service.get (/Users/xema/projects/tottus/products/lib/api/products/service.js:15:19)
        at Object.getProduct (/Users/xema/projects/tottus/products/lib/api/products/controller.js:9:35)
        at preHandlerCallback (/Users/xema/projects/tottus/products/node_modules/fastify/lib/handleRequest.js:95:30)
        at handler (/Users/xema/projects/tottus/products/node_modules/fastify/lib/handleRequest.js:79:5)
        at handleRequest (/Users/xema/projects/tottus/products/node_modules/fastify/lib/handleRequest.js:18:5)
        at onRunMiddlewares (/Users/xema/projects/tottus/products/node_modules/fastify/fastify.js:446:5)
        at middlewareCallback (/Users/xema/projects/tottus/products/node_modules/fastify/fastify.js:434:7)
        at next (/Users/xema/projects/tottus/products/node_modules/fastify/lib/hookRunner.js:8:7)`

**Comment by Babanila** [comment]
The query parameter for getting a product with `productId` and `priceCountry` will throw an error because it can only be used in conjunction with the `priceCurrency` parameter. ([See Docs ](https://docs.commercetools.com/http-api-projects-products#get-product-by-id))
@skyriakou @xemayebenes

**Comment by xemayebenes** [comment]
@Babanila 
If i add the `priceCurrency `, i get the error `this.priceCurrency is not a function`

```js
const product = await client.execute({
      uri: requestBuilder.products
        .parse({
          id: '053ac5dc-1e1f-4241-a0e8-f1ebc7096111',
          priceCountry: 'CL',
          priceCurrency: 'CLP',
        })

        .build(),
      method: 'GET',
    });
```

**Comment by Babanila** [comment]
@xemayebenes
The product method cannot be used to get products based on `priceCountry` and `priceCurrency`. Please use the `productProjections` method instead:
```js
const product = await client.execute({
      uri: requestBuilder.productProjections
        .parse({
          id: '053ac5dc-1e1f-4241-a0e8-f1ebc7096111',
          priceCountry: 'CL',
          priceCurrency: 'CLP',
        })

        .build(),
      method: 'GET',
    });
```
