### ISSUE TITLE
[product-json-to-csv] Handle conflicting attribute names

### ISSUE THREAD

**Issue by junajan** [commercetools/nodejs#868]
### Support reference number

SUPPORT-4036

### Description
If the exported product has an attribute named as `productType` or any basic product property, we override that property with a value from the attribute.

This can lead to an error while doing a full export - eg. exporting to an incorrect productType file stream:
```
/app/node_modules/@commercetools/product-json-to-csv/lib/writer.js:128
    fileStream.write(`${csvData}\n`);
               ^

TypeError: Cannot read property 'write' of undefined
    at productStream.each.product (/app/node_modules/@commercetools/product-json-to-csv/lib/writer.js:128:16)
    at /app/node_modules/highland/lib/index.js:1847:13
    at Stream.s._send (/app/node_modules/highland/lib/index.js:1549:9)
    at Stream.write (/app/node_modules/highland/lib/index.js:1650:18)
    at Stream._send (/app/node_modules/highland/lib/index.js:974:26)
    at push (/app/node_modules/highland/lib/index.js:1515:19)
    at /app/node_modules/highland/lib/index.js:1808:13
    at Stream.s._send (/app/node_modules/highland/lib/index.js:1549:9)
    at Stream.write (/app/node_modules/highland/lib/index.js:1650:18)
    at Stream._send (/app/node_modules/highland/lib/index.js:974:26)
    at push (/app/node_modules/highland/lib/index.js:1515:19)
    at /app/node_modules/highland/lib/index.js:2146:13
    at Stream.s._send (/app/node_modules/highland/lib/index.js:1549:9)
    at Stream.write (/app/node_modules/highland/lib/index.js:1650:18)
    at Stream._send (/app/node_modules/highland/lib/index.js:974:26)
    at Stream.write (/app/node_modules/highland/lib/index.js:1650:18)
ERR: write EPIPE

Process exited with code (1)
```

After discussing with @stmeissner and @daern91 we decided to prefix conflicting attribute names with `attribute.` so the productType attribute would be exported to a column named as `attribute.productType`. 

**NOTE:** We should check also importer if it can handle these cases and it should be handled in both monorepo and old [csv-sync](https://github.com/sphereio/sphere-node-product-csv-sync/).

**Comment by junajan** [comment]
This Issue was fixed by #869
